# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLAD_config = debug
  GLFW_config = debug
  IMGUI_config = debug
  ASSIMP_config = debug
  GLM_config = debug
  IMGUIZMO_config = debug
  Engine_config = debug
  Project_config = debug

else ifeq ($(config),release)
  GLAD_config = release
  GLFW_config = release
  IMGUI_config = release
  ASSIMP_config = release
  GLM_config = release
  IMGUIZMO_config = release
  Engine_config = release
  Project_config = release

else ifeq ($(config),dist)
  GLAD_config = dist
  GLFW_config = dist
  IMGUI_config = dist
  ASSIMP_config = dist
  GLM_config = dist
  IMGUIZMO_config = dist
  Engine_config = dist
  Project_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLAD GLFW IMGUI ASSIMP GLM IMGUIZMO Engine Project

.PHONY: all clean help $(PROJECTS) Engine Projects _External

all: $(PROJECTS)

Engine: Engine

Projects: Project

_External: ASSIMP GLAD GLFW GLM IMGUI IMGUIZMO

GLAD:
ifneq (,$(GLAD_config))
	@echo "==== Building GLAD ($(GLAD_config)) ===="
	@${MAKE} --no-print-directory -C Engine/External/glad -f Makefile config=$(GLAD_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Engine/External/glfw -f Makefile config=$(GLFW_config)
endif

IMGUI:
ifneq (,$(IMGUI_config))
	@echo "==== Building IMGUI ($(IMGUI_config)) ===="
	@${MAKE} --no-print-directory -C Engine/External/imgui -f Makefile config=$(IMGUI_config)
endif

ASSIMP:
ifneq (,$(ASSIMP_config))
	@echo "==== Building ASSIMP ($(ASSIMP_config)) ===="
	@${MAKE} --no-print-directory -C Engine/External/assimp -f Makefile config=$(ASSIMP_config)
endif

GLM:
ifneq (,$(GLM_config))
	@echo "==== Building GLM ($(GLM_config)) ===="
	@${MAKE} --no-print-directory -C Engine/External/glm -f Makefile config=$(GLM_config)
endif

IMGUIZMO:
ifneq (,$(IMGUIZMO_config))
	@echo "==== Building IMGUIZMO ($(IMGUIZMO_config)) ===="
	@${MAKE} --no-print-directory -C Engine/External/imguizmo -f Makefile config=$(IMGUIZMO_config)
endif

Engine: GLAD GLFW IMGUI ASSIMP GLM IMGUIZMO
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE} --no-print-directory -C Engine -f Makefile config=$(Engine_config)
endif

Project: Engine GLAD GLFW IMGUI ASSIMP GLM IMGUIZMO
ifneq (,$(Project_config))
	@echo "==== Building Project ($(Project_config)) ===="
	@${MAKE} --no-print-directory -C Project -f Makefile config=$(Project_config)
endif

clean:
	@${MAKE} --no-print-directory -C Engine/External/glad -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/External/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/External/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/External/assimp -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/External/glm -f Makefile clean
	@${MAKE} --no-print-directory -C Engine/External/imguizmo -f Makefile clean
	@${MAKE} --no-print-directory -C Engine -f Makefile clean
	@${MAKE} --no-print-directory -C Project -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLAD"
	@echo "   GLFW"
	@echo "   IMGUI"
	@echo "   ASSIMP"
	@echo "   GLM"
	@echo "   IMGUIZMO"
	@echo "   Engine"
	@echo "   Project"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"